version: '3'

services:
  wordpress:
    container_name: pistachio_wordpress
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    image: andreccosta/wordpress-xdebug
    ports:
      - "8082:80"
    env_file:
      - default.env
    volumes:
      - ./wordpress:/var/www/html/
      - .:/var/www/html/wp-content/plugins/pistachio
  db:
    container_name: pistachio_mysql
    image: mysql:5.7
    env_file:
      - default.env

  composer:
    restart: "no"
    image: composer
    command: install
    volumes:
      - .:/app
